// Pixel art: edit the rows directly; every row of a `.layer` is 20 cells wide.
// Letters are palette roles: . clear, k ink, d shade, o body, h light, w white, a accent
// (and the shared prop neutrals: c light grey, n mid grey, m dark grey, b water blue).

extension MascotRig {
    /// Claude — a terracotta spark: a round coral core with a cream starburst of irregular rays around it, like
    /// the Claude mark, and a small blushing face. Working, the rays spin; thinking, they turn slowly (Claude's
    /// own spinner); failing, they go out (grey) and it sheds a tear. It floats — no feet.
    static let claude = MascotRig(
        palette: MascotPalette(ink: 0x3A1A10, shade: 0xB5532F, body: 0xD97757,
                               light: 0xE8977A, white: 0xF6E3D6, accent: 0xF4A48C),
        waistRow: 11,
        body: .layer(top: 5, """
            ........oooo........
            .......ohhooo.......
            ......ohhooooo......
            .....ohhooooooo.....
            .....ohoooooood.....
            .....oooooooood.....
            .....oooooooodd.....
            ......oooooodd......
            .......oooodd.......
            ........dddd........
            """),
        faceOrigin: MascotRig.Point(x: 5, y: 7),
        faces: [
            .open: PixelArt("""
                ..........
                ..k....k..
                ..k....k..
                a...kk...a
                """),
            .blink: PixelArt("""
                ..........
                ..........
                .kk....kk.
                a...kk...a
                """),
            .happy: PixelArt("""
                ..........
                ..k....k..
                .k.k..k.k.
                a..k..k..a
                ....kk....
                """),
            .wince: PixelArt("""
                ..........
                .k......k.
                ..k....k..
                .k..kk..k.
                """),
            .sad: PixelArt("""
                ..........
                .k.k..k.k.
                ..k....k..
                .k.k..k.k.
                ....kk....
                """),
            .up: PixelArt("""
                ..k....k..
                ..k....k..
                ..........
                a...kk...a
                """),
        ],
        halo: [
            .layer(top: 0, """
                ..........w.........
                ..........w.........
                ..........w.........
                ......w...w..w......
                ......ww..w.ww......
                ..ww...w..w.w...ww..
                ...ww..w....w..ww...
                ....www......www....
                ....................
                ....................
                ..wwww........wwww..
                ....................
                ....www......www....
                ...ww..w....w..ww...
                ..ww...w..w.w...ww..
                ......ww..w.ww......
                ......w...w..w......
                ..........w.........
                ..........w.........
                """),
            .layer(top: 1, """
                ............w.......
                ...........ww.......
                ........w..w........
                ....w...w..w...w....
                .....w..w..w..w.....
                ......w......w......
                .................ww.
                ..wwww........wwww..
                ....................
                ....................
                ..wwww........www...
                .ww.................
                ......w......w......
                .....w..w..w..w.....
                ........w..w...w....
                ........w..w....w...
                .......ww..w........
                .......w............
                """),
            .layer(top: 2, """
                .....w........w.....
                .....ww..w...ww.....
                ......ww.w..ww......
                .......w.ww.w.......
                ...ww..w....w..ww...
                ....www......www....
                ....................
                ....................
                wwwwww........wwwww.
                ....................
                ....www......www....
                ...ww..w....w..ww...
                .......w..w.w.......
                ......ww..w.ww......
                .....ww...w..ww.....
                .....w....w...w.....
                """),
            .layer(top: 1, """
                .......w............
                .......ww...........
                ........w..w....w...
                ....w...w..w...w....
                .....w..w..w..w.....
                ......w......w......
                .ww.................
                ..wwww........wwww..
                ....................
                ....................
                ...www........wwww..
                .................ww.
                ......w......w......
                .....w..w..w..w.....
                ....w...w..w........
                ........w..w........
                ........w..ww.......
                ............w.......
                """),
            .layer(top: 1, """
                .........w..........
                .........w..........
                ......w..w...w......
                ......ww.w..ww......
                ..ww...w.ww.w...ww..
                ...ww..w....w..ww...
                ....www......www....
                ....................
                ....................
                ...www........wwww..
                ....................
                ....www......www....
                ...ww..w....w..ww...
                ..ww...w..w.w...ww..
                ......ww..w.ww......
                ......w...w..w......
                ..........w.........
                ..........w.........
                ..........w.........
                """),
            .layer(top: 1, """
                ............w.......
                ........w..ww.......
                ...w....w..w........
                ....w...w..w........
                .....w..w..w..w.....
                ......w......w......
                .................ww.
                ...www........wwww..
                ....................
                ....................
                ..wwww........wwww..
                .ww.................
                ......w......w......
                .....w..w..w..w.....
                ....w...w..w...w....
                ........w..w........
                .......ww...........
                .......w............
                """),
            .layer(top: 2, """
                .....w...w....w.....
                .....ww..w...ww.....
                ......ww.w..ww......
                .......w.ww.w.......
                ...ww..w....w..ww...
                ....www......www....
                ....................
                ....................
                .wwwww........wwwwww
                ....................
                ....www......www....
                ...ww..w....w..ww...
                .......w..w.w.......
                ......ww..w.ww......
                .....ww...w..ww.....
                .....w....w...w.....
                """),
            .layer(top: 1, """
                .......w............
                .......ww..w........
                ........w..w........
                ........w..w...w....
                .....w..w..w..w.....
                ......w......w......
                .ww.................
                ..wwww........www...
                ....................
                ....................
                ..wwww........wwww..
                .................ww.
                ......w......w......
                .....w..w..w..w.....
                ....w...w..w...w....
                ...w....w..w........
                ...........ww.......
                ............w.......
                """),
        ],
        errorTint: [.white: .propMid],
        tearOrigin: MascotRig.Point(x: 7, y: 12),
        bubbleOrigin: MascotRig.Point(x: 0, y: 0),
        sparkleSpots: [.init(x: 2, y: 16), .init(x: 17, y: 15), .init(x: 17, y: 3), .init(x: 2, y: 3)]
    )
}
