// Pixel art: edit the rows directly; every row of a `.layer` is 20 cells wide.
// Letters are palette roles: . clear, k ink, d shade, o body, h light, w white, a accent
// (and the shared prop neutrals: c light grey, n mid grey, m dark grey, b water blue).

extension MascotRig {
    /// Codex — a round, six-lobed puffy cloud like the app icon's (lobes tilted the same way: the top-left one
    /// highest, the bottom-right one lowest), shaded in its gradient: a lilac crown, cornflower blue through the
    /// middle, ultramarine underneath, each lobe lit along its upper rim. Its face is the terminal prompt: `>` squints, `_`
    /// is the mouth and blinks like a cursor. Thinking, it types `...` after the prompt; failing, it turns into a
    /// grey rain cloud (`x_`) and drizzles. It floats — no feet.
    static let codex = MascotRig(
        palette: MascotPalette(ink: 0x2A2CE6, shade: 0x3A4DFF, body: 0x6388FF,
                               light: 0x9C94FF, white: 0xFFFFFF, accent: 0xC8ACFF),
        waistRow: 13,
        body: .layer(top: 2, """
            ......aaaa..........
            .....aaaaah.........
            ....aaahhhhh.ahh....
            ....ahhhhhhhhhhhh...
            ...ahhhhhhhhhhhhoo..
            ..ahhhhhhhhhhooooo..
            .ahhhooooooooooood..
            .hhoooooooooooooo...
            .doooooooooooooooh..
            ..doooooooooooooooh.
            ...oooooooooooooooo.
            ...dooooooddddddddk.
            ...kdddddddddddddk..
            ....kdddkkdddddkk...
            .....kkk..kkkkkk....
            ...........kkkk.....
            """),
        faceOrigin: MascotRig.Point(x: 5, y: 8),
        faces: [
            .open: PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww...wwww..
                """),
            .blink: PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww.........
                """),
            .happy: PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww..w..w..
                ww....ww...
                """),
            .wince: PixelArt("""
                w.........w
                .w.......w.
                ..w.....w..
                .w.......w.
                w...www...w
                """),
            .sad: PixelArt("""
                ...........
                w.w........
                .w.........
                w.w........
                .....www...
                """),
            .up: PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww...wwww..
                """),
        ],
        thinkFaces: [
            PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww...w.....
                """),
            PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww...w.w...
                """),
            PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww...w.w.w.
                """),
            PixelArt("""
                ww.........
                .ww........
                ..ww.......
                .ww........
                ww.........
                """),
        ],
        cursorBlink: true,
        errorTint: [.accent: .propLight, .light: .propMid, .body: .propMid, .shade: .propDark, .ink: .propDark],
        rainColumns: [7, 10, 13],
        bubbleOrigin: MascotRig.Point(x: 0, y: 0),
        sparkleSpots: [.init(x: 1, y: 15), .init(x: 18, y: 16), .init(x: 17, y: 2), .init(x: 3, y: 1)]
    )
}
