// Pixel art: edit the rows directly; every row of a `.layer` is 20 cells wide.
// Letters are palette roles: . clear, k ink, d shade, o body, h light, w white, a accent.

extension MascotRig {
    /// Generic — "Blob": a neutral grey gumdrop for agents that have no character of their own yet.
    static let generic = MascotRig(
        palette: MascotPalette(ink: 0x1B1D24, shade: 0x6F7488, body: 0xAEB3C3,
                               light: 0xDEE1EA, white: 0xFFFFFF, accent: 0x9ED6FF),
        waistRow: 16,
        body: .layer(top: 8, """
            ........hhoo........
            ......hhhooooo......
            .....hhwhoooood.....
            ....hhwooooooood....
            ....hooooooooood....
            ....oookooookood....
            ....oookooookood....
            ....oooookkooood....
            ....oooooooooodd....
            ...dddddddddddddd...
            """),
        arms: [
            .rest: .layer(top: 13, """
                ...h............h...
                ...o............o...
                """),
            .waveA: .layer(top: 10, """
                .................h..
                .................o..
                ................o...
                ...h................
                ...o................
                """),
            .waveB: .layer(top: 9, """
                ................h...
                ................o...
                ................o...
                ................o...
                ...h................
                ...o................
                """),
            .up: .layer(top: 10, """
                ..h..............h..
                ..o..............o..
                ...o............o...
                """),
            .swingA: .layer(top: 11, """
                ................h...
                ................o...
                ...o................
                ...o................
                ..h.................
                """),
            .swingB: .layer(top: 11, """
                ...h................
                ...o................
                ................o...
                ................o...
                .................h..
                """),
            .droop: .layer(top: 14, """
                ...o............o...
                ..h..............h..
                """),
        ],
        legs: [
            .stand: .layer(top: 17, """
                .......d....d.......
                .......d....d.......
                ......dd....dd......
                """),
            .stepA: .layer(top: 17, """
                .......d....d.......
                ......dd....d.......
                ............dd......
                """),
            .stepB: .layer(top: 17, """
                .......d....d.......
                .......d....dd......
                ......dd............
                """),
            .tuck: .layer(top: 17, """
                .......d....d.......
                ......dd....dd......
                """),
            .sit: .layer(top: 19, """
                ....ddd......ddd....
                """),
        ],
        faceOrigin: MascotRig.Point(x: 5, y: 12),
        faces: [
            .open: PixelArt("""
                oooooooooo
                ookooookoo
                ookooookoo
                ooookkoooo
                """),
            .blink: PixelArt("""
                oooooooooo
                oooooooooo
                okkooookko
                ooookkoooo
                """),
            .happy: PixelArt("""
                oooooooooo
                ookooookoo
                okokookoko
                ooookkoooo
                """),
            .wince: PixelArt("""
                oooooooooo
                okooooooko
                ookooookoo
                okookkooko
                """),
            .sad: PixelArt("""
                kokooookok
                okooooooko
                kokooookok
                ooookkoooo
                """),
            .up: PixelArt("""
                oookooooko
                oookooooko
                oooooooooo
                oooookoooo
                """),
        ],
        tearOrigin: MascotRig.Point(x: 7, y: 17)
    )
}
